images: svg
	@echo "=============================================="
	@echo " Converted all images !"
	@echo "=============================================="

svg:
	MYDIR=icons_raw/
	ls $(MYDIR)/*
	@echo $^