images: 
	@cd builder/ && poetry run python builder/main.py
	@echo "=============================================="
	@echo " Converted all images to .bin format !"
	@echo "=============================================="


