[1] # General-purpose web sources
reddit = "reddit.bin"
youtube = "youtube.bin"
twitch = "twitch.bin"
facebook = "facebook.bin"
twitter = "x.bin"
vimeo = "vimeo.bin"
dailymotion = "dailymotion.bin"
netflix = "netflix.bin"
primevideo = "primevideo.bin"
disneyplus = "disneyplus.bin"

[2] # General-purpose web sources (continued)
imdb = "imdb.bin"
metacafe = "metacafe.bin"
stackoverflow = "stackoverflow.bin"
github = "github.bin"
google = "google.bin"
w3 = "w3.bin"

[3] # Music (apps and webplayers)
spotify = "spotify.bin"
deezer = "deezer.bin"
tidal = "tidal.bin"
qobuz = "qobuz.bin"
youtube_music = "youtubemusic.bin"
soundcloud = "soundcloud.bin"
bandcamp = "bandcamp.bin"
vlc = "vlc.bin"
applemusic = "applemusic.bin"
amazonmusic = "amazonluna.bin"
audacity = "audacity.bin"
beats = "beats.bin"
lastfm = "lastfm.bin"
tunein = "tuneIn.bin"
stitcher = "stitcher.bin"
playerfm = "playerfm.bin"
pocketcasts = "pocketcasts.bin"
googlepodcasts = "googlepodcasts.bin"
applepodcasts = "applepodcasts.bin"

[4] # VoIP services
discord = "discord.bin"
skype = "skype.bin"
slack = "slack.bin"
teams = "teams.bin"
zoom = "zoom.bin"
messenger = "messenger.bin"
telegram = "telegram.bin"
whatsapp = "whatsapp.bin"
mewe = "mewe.bin"
qik = "qik.bin"
kik = "kik.bin"
line = "lineapp.bin"
wechat = "wechat.bin"
googlemeet = "googlemeet.bin"
googlechat = "googlechat.bin"
icq = "icq.bin"
aim = "aim.bin"