/** ================================================================
 * @file    Core/Inc/hal/init.hpp
 *
 * @brief   init.hpp define low level initialization steps of the MCU.
 *
 * @date    26-05-2025
 *
 * @version 1.0.0
 *
 * @author  l.heywang (leonard.heywang@proton.me)
 *
 *  ================================================================
 */
#ifndef __DEF_INIT
#define __DEF_INIT

/* -----------------------------------------------------------------
 * INCLUDES
 * -----------------------------------------------------------------
 */

#include "stm32f3xx_hal.h"

/* -----------------------------------------------------------------
 * INITIALIZATION FUNCTIONS
 * -----------------------------------------------------------------
 */

/*
 * Theses functions are copied from the main.c file (generated by ST).
 * This is done to export them for the global project, independent of the MCU.
 */
namespace init{
	extern ADC_HandleTypeDef hadc1;
	extern I2C_HandleTypeDef hi2c2;
	extern TSC_HandleTypeDef htsc;
	extern UART_HandleTypeDef huart3;
	extern PCD_HandleTypeDef hpcd_USB_FS;

	void SystemClock_Config(void);
	void MX_GPIO_Init(void);
	void MX_ADC_Init(void);
	void MX_I2C_Init(void);
	void MX_TSC_Init(void);
	void MX_USART_UART_Init(void);
	void MX_USB_PCD_Init(void);

	/**
	 * @brief 	Initialize the whole peripherals of the device
	 *
	 * @param 	None
	 *
	 * @return 	None
	 */
	void full(void);

	/* -----------------------------------------------------------------
	 * Error handler function
	 * -----------------------------------------------------------------
	 */

	void Error_Handler(void);
}

#endif
