# This file bind icons ID with apps. This enable the autogeneration of the icons easier !

[icons]

1 = "MeWe"
2 = "AfterEffects"
3 = "Animate"
4 = "Audition"
5 = "Bridge"
6 = "Illustrator"
7 = "InDesign"
8 = "Lightroom"
9 = "Photoshop"
10 = "PremierePro"
11 = "Distribute"
12 = "Aim"
13 = "AmazonLuna"
14 = "Prime"
15 = "PrimeVideo"
16 = "AMD"
17 = "Analogue"
18 = "Anchor"
19 = "ApplePodcasts"
20 = "Audacity"
21 = "Authy"
22 = "Bandcamp__old"
23 = "Bandcamp"
24 = "BBC__old"
25 = "BBC"
26 = "Beats"
27 = "BeyondCorp"
28 = "Bilibili"
29 = "NextTrack"
30 = "NextSong"
31 = "PlayPause"
32 = "Pause"
33 = "Play"
34 = "Stop"
35 = "Byte"
36 = "Chrome"
37 = "Cinema4D"
38 = "Controller"
39 = "Crunchyroll"
40 = "CryEngine"
41 = "DailyMotion"
42 = "Deezer"
43 = "Disk"
44 = "Dice5"
45 = "DigitalOcean"
46 = "Discord"
47 = "DisneyPlus"
48 = "EAPlay"
49 = "EpicGames"
50 = "ESEA"
51 = "FDroid"
52 = "Facebook"
53 = "Messenger"
54 = "FitBit"
55 = "Funimation"
56 = "Gabbr"
57 = "NVIDIA"
58 = "GitHub__old"
59 = "GitHub"
60 = "GOG"
61 = "GoogleBuzz"
62 = "ChromeCast"
63 = "GoogleChat"
64 = "GoogleHangouts__old"
65 = "GoogleHangouts"
66 = "GoogleMeet__old"
67 = "GoogleHome"
68 = "Google"
69 = "GoogleMeet"
70 = "GooglePodcasts"
71 = "Stadia"
72 = "GoogleTalk"
73 = "GrooveShark"
74 = "HBOMax"
75 = "Hulu"
76 = "ICQ"
77 = "IMDb"
78 = "iMessage"
79 = "Private"
80 = "IQ"
81 = "AppleMusic"
82 = "KakaoTalk"
83 = "Kick"
84 = "Kik__old"
85 = "Kik"
86 = "Kodi"
87 = "LastFM"
88 = "LineApp"
89 = "Loom"
90 = "Firefox"
91 = "GoogleMessages"
92 = "MetaCafe"
93 = "Microsoft"
94 = "Midi"
95 = "MSN"
96 = "Mubi"
97 = "Unmute"
98 = "Mute"
99 = "Netflix"
100 = "NicoNico"
101 = "NicoNicoLive"
102 = "NintendoNetwork"
103 = "NintedoSwitch"
104 = "OBS"
105 = "OpenAI"
106 = "Origin"
107 = "OSMC"
108 = "Overcast"
109 = "PingChat"
110 = "PlayerFM"
111 = "PlayStation"
112 = "PocketCasts"
113 = "Mail"
114 = "Qik"
115 = "Qobuz"
116 = "QQ"
117 = "RDIO"
118 = "ReasonStudios"
119 = "Reddit"
120 = "RIOT"
121 = "Shadow"
122 = "Shazam"
123 = "Skype"
124 = "Skype__old"
125 = "Slack"
126 = "Snapchat"
127 = "SoundCloud"
128 = "Spark"
129 = "Speaker"
130 = "Spinrilla"
131 = "Spotify"
132 = "SquareEnix"
133 = "StackOverflow"
134 = "Steam"
135 = "Stitcher__old"
136 = "Stitcher"
137 = "Streaming"
138 = "StreamPlay"
139 = "Telegram__old"
140 = "Telegram"
141 = "Threads"
142 = "Tidal"
143 = "TikTok"
144 = "Tinder"
145 = "Trello"
146 = "TuneIn"
147 = "Twitch"
148 = "Twitter"
149 = "Ubisoft"
150 = "UnrealEngine"
151 = "Viddler"
152 = "Vimeo"
153 = "VLC"
154 = "Volume100"
155 = "Volume66"
156 = "Volume33"
157 = "Volume0"
158 = "VolumeMute"
159 = "Vortex__old"
160 = "Vortex"
161 = "W3"
162 = "WeChat"
163 = "WeChatPlay"
164 = "WeTV"
165 = "Whatsapp"
167 = "X"
168 = "Xbox"
169 = "Youtube"
170 = "YoutubeGaming__old"
171 = "YoutubeGaming2__old"
172 = "YoutubeGaming"
173 = "YoutubeMusic"
174 = "YoutubeStudio"
175 = "YoutubeTV"
176 = "ZCool__old"
177 = "ZCool"
178 = "Zoom__old"
179 = "Zoom"
