#include "gtest/gtest.h"
#include "parser/parser.h"

/**
 * ===============================================================
 * FIRST : STRING FORMATION ERRORS
 * ===============================================================
 */

TEST(Parser, InvalidBufferCheck)
{
	// Invalid buffer test
	char *buf = 0;
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -1);
}

TEST(Parser, InvalidStructCheck)
{
	// Invalid struct test
	char buf[1024] = "Hello World !";
	struct CMD *command = 0;

	int retval = parser(buf, command);

	ASSERT_EQ(retval, -1);
}


TEST(Parser, TokenStartNotFound)
{
	// No START token
	char buf[1024] = "YouWon'tFindStartGna";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -10);
}

TEST(Parser, TokenCommandNotFound)
{
	// No command found
	char buf[1024] = "START;GnaGnaGnaGnaGna";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -11);
	ASSERT_EQ(command.result, NACK);
}

TEST(Parser, TokenLengthNotFound)
{
	// No Length token
	char buf[1024] = "START;SHUTD;000:TUTUTUTUTUTUTUTUTTU";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -12);
}

TEST(Parser, TokenCRCNotFound)
{
	// No CRC token
	char buf[1024] = "START;SHUTD;000;;DEADBEEF:";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -14);
}

TEST(Parser, TokenEndNotFound)
{
	// No END token
	char buf[1024] = "START;SHUTD;000;;DEADBEEF;EMD";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

/**
 * ===============================================================
 * SECOND : COMMAND PARSING NAMES
 * ===============================================================
 */

TEST(Parser, CommandSHUTDParsing)
{
	//SHUTD command
	char buf[1024] = "START;SHUTD;000;;765eb2c0;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, SHUTD);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandRINITParsing)
{
	// RINIT command
	char buf[1024] = "START;RINIT;000;;f6e762a6;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, RINIT);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandCONNCParsing)
{
	// CONNC command
	char buf[1024] = "START;CONNC;000;;3c3da2b3;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, CONNC);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandASYNCParsing)
{
	// ASYNC command
	char buf[1024] = "START;ASYNC;000;;916255ac;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, ASYNC);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandUICONParsing)
{
	// UICON command
	char buf[1024] = "START;UICON;000;;2b525a75;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, UICON);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandSLPOSParsing)
{
	// SLPOS command
	char buf[1024] = "START;SLPOS;000;;b68ad8c8;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, SLPOS);
	ASSERT_EQ(command.direction, TX);
}

TEST(Parser, CommandDCONFParsing)
{
	// DCONF command
	char buf[1024] = "START;DCONF;000;;4a796c5a;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, 0);
	ASSERT_EQ(command.type, DCONF);
	ASSERT_EQ(command.direction, TX);
}

/**
 * ===============================================================
 * THIRD : Lenghts and PAYLOADS
 * ===============================================================
 */

TEST(Parser, CommandLengthParsing000)
{
	// 0 char payload
	char buf[1024] = "START;DCONF;000;;4a796c5a;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 0);

	ASSERT_EQ(retval, 0);
}

TEST(Parser, CommandLengthParsing001)
{
	// 1 char payload
	char buf[1024] = "START;DCONF;001;A;85913136;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 1);
	EXPECT_STREQ((char*)command.payload, "A");
	ASSERT_EQ(retval, 0);
}

TEST(Parser, CommandLengthParsing001E)
{
	// 1 char payload with issue.
	char buf[1024] = "START;DCONF;;;4bbb066d;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -12);
}

TEST(Parser, CommandInvalidLength)
{
	// 1 char payload with issue.
	char buf[1024] = "START;DCONF;AAA;e;4bbb066d;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 0);
	ASSERT_EQ(retval, -13);
}

TEST(Parser, CommandInvalidCRC)
{
	// 1 char payload with issue.
	char buf[1024] = "START;DCONF;001;e;nnnnnnnn;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 1);
	ASSERT_EQ(retval, -15);
}

TEST(Parser, CommandLengthParsing010)
{
	// 10 char payload
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;31d96751;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 10);
	EXPECT_STREQ((char*)command.payload, "AAAAAAAAAA");
	ASSERT_EQ(retval, 0);
}

TEST(Parser, CommandLengthParsing100)
{
	// 100 char payload
	char buf[1024] = "START;DCONF;100;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;da0ad5b9;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 100);
	EXPECT_STREQ((char*)command.payload, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	ASSERT_EQ(retval, 0);
}

TEST(Parser, CommandLengthParsing500)
{
	// 500 char payload
	char buf[1024] = "START;DCONF;500;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;ffd15417;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 500);
	EXPECT_STREQ((char*)command.payload, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	ASSERT_EQ(retval, 0);
}

TEST(Parser, CommandLengthParsing995)
{
	// Full length payload
	char buf[1025] = "START;DCONF;995;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;9da7896c;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.len, 995);
	EXPECT_STREQ((char*)command.payload, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	ASSERT_EQ(retval, 0);
}

/**
 * ===============================================================
 * FOURTH : CRC32 fetching
 * ===============================================================
 */

TEST(Parser, CommandCrcParsing1)
{
	// DEADBEEF crc
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;DEADBEEF;END";
	struct CMD command;

	parser(buf, &command);

	ASSERT_EQ(command.crc, 0xdeadbeef);
}

TEST(Parser, CommandCrcParsing2)
{
	// deadbeef crc
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;deadbeef;END";
	struct CMD command;

	parser(buf, &command);

	ASSERT_EQ(command.crc, 0xdeadbeef);
}

TEST(Parser, CommandCrcParsing3)
{
	// 12345678 crc
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;12345678;END";
	struct CMD command;

	parser(buf, &command);

	ASSERT_EQ(command.crc, 0x12345678);
}

TEST(Parser, CommandCrcParsing4)
{
	// 9abcdef1 crc
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;9abcdef1;END";
	struct CMD command;

	parser(buf, &command);

	ASSERT_EQ(command.crc, 0x9abcdef1);
}

TEST(Parser, CRCComp1)
{
	char buf[1024] = "START;DCONF;010;AAAAAAAAAA;31d96751;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(command.crc, 0x31d96751);
	ASSERT_EQ(retval, 0);
}

/**
 * ===============================================================
 * FOURTH : CRC32 comparison
 * ===============================================================
 */

TEST(Parser, CRCError1)
{
	// Sub 1 to the crc
	char buf[1024] = "START;DCONF;000;;4a796c59;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError2)
{
	// 1 char payload changed
	char buf[1024] = "START;DCONF;001;_;85913136;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError3)
{
	// corrupted a single bit
	char buf[1024] = "START;DCONF;000;;4bba066d;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError4)
{
	// Changed an A to B
	char buf[1024] = "START;DCONF;010;AAAAAAAAAB;31d96751;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError5)
{
	// Added 1 to CRC
	char buf[1024] = "START;DCONF;100;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;da0ad5ba;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError6)
{
	// changed an A in the middle
	char buf[1024] = "START;DCONF;500;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;ffd15417;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}

TEST(Parser, CRCError7)
{
	// changed case of an A
	char buf[1025] = "START;DCONF;995;AAAAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;9da7896c;END";
	struct CMD command;

	int retval = parser(buf, &command);

	ASSERT_EQ(retval, -16);
}
